stages:          
  - run_webhook


webhook-job:   
  stage: run_webhook
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

  image: python:3.12

  before_script: pip install .
  script: karlov_lunch -s $SLACK_WEBHOOK