name: Run karlov_lunch Webhook

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "30 9 * * 1-5" # runs every weekday on 9:30

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install App
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run Webhook
      env:
        WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: karlov_lunch -s "$WEBHOOK"
    
